# Generated by Django 5.0.3 on 2024-03-25 18:24

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'categories'},
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_methods',
            field=models.CharField(choices=[('Post', 'Post'), ('SELF-DELIVERY', 'SELF-DELIVERY'), ('COURIER', 'COURIER')], max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CARD ONLINE', 'CARD ONLINE'), ('CASH', 'CASH'), ('CARD OFFLINE', 'CARD OFFLINE')], max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('CANCELED ', 'CANCELED'), ('IN PROCESS', 'IN PROCESS'), ('PAID', 'PAID')], default='IN PROCESS', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ON THE WAY', 'ON THE WAY '), ('REFUSE', 'REFUSE'), ('IN PROCESS', 'IN PROCESS'), ('PACKED', 'PACKED'), ('DELIVERED', 'DELIVERED')], max_length=100),
        ),
    ]
